// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Coevery.DeveloperTools.CodeGeneration.CodeGenerationTemplates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class ApiControllerTemplate : ApiControllerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing System.Collections.Generic;\r\nusing System.Web.Http;\r\nusing ");
            
            #line 8 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(".Models;\r\n\r\nnamespace ");
            
            #line 10 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(".Controllers \r\n{\r\n    public class ");
            
            #line 12 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("ApiController : ApiController {\r\n        public IEnumerable<");
            
            #line 13 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord> GetAllLeads() {\r\n            var ");
            
            #line 14 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("s = new List<");
            
            #line 14 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord> {\r\n                new ");
            
            #line 15 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 1, Subject = \"Long-term Sitefinity partner\", Description = \"\", C" +
                    "ompanyName = \"\"},\r\n                new ");
            
            #line 16 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 2, Subject = \"Web Part Needed\", Description = \"I need a w\", Comp" +
                    "anyName = \"\"},\r\n                new ");
            
            #line 17 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 3, Subject = \"DNN convert\", Description = \"\", CompanyName = \"\"}," +
                    "\r\n                new ");
            
            #line 18 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 4, Subject = \"Magento Specialist\", Description = \"\", CompanyName" +
                    " = \"DiBowebsites\"},\r\n                new ");
            
            #line 19 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 5, Subject = \"Significant Amount of Custom DNN Module Creation \"" +
                    ", Description = \"Message: \", CompanyName = \"\"},\r\n                new ");
            
            #line 20 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 6, Subject = \"Costs to copy the air b\'n\'b site \", Description = " +
                    "\"\", CompanyName = \"\"},\r\n                new ");
            
            #line 21 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 7, Subject = \"build a bilingual (Chinese & English) website\", De" +
                    "scription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 22 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 8, Subject = \"need to offshore some small projects\", Description" +
                    " = \"客户说有很多小项目需\", CompanyName = \"\"},\r\n                new ");
            
            #line 23 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 9, Subject = \"Fixing the issues for New Site\", Description = \"Me" +
                    "ssage: \", CompanyName = \"BagsandFashion\"},\r\n                new ");
            
            #line 24 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 10, Subject = \"Senior developer in advanced C#\", Description = \"" +
                    "\", CompanyName = \"matogen.com\"},\r\n                new ");
            
            #line 25 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 11, Subject = \"Nop Theme\", Description = \"\", CompanyName = \"\"},\r" +
                    "\n                new ");
            
            #line 26 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 12, Subject = \"Job posting website\", Description = \"I need .ne\"," +
                    " CompanyName = \"\"},\r\n                new ");
            
            #line 27 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 13, Subject = \"Quotation for a control library\", Description = \"" +
                    "\", CompanyName = \"西门子\"},\r\n                new ");
            
            #line 28 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 14, Subject = \"Two Full Time Silverlight Engineers \", Descriptio" +
                    "n = \"I have see\", CompanyName = \"\"},\r\n                new ");
            
            #line 29 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 15, Subject = \"Calendar Carousel on Drupal Website\", Description" +
                    " = \"\", CompanyName = \"webconcept.de\"},\r\n                new ");
            
            #line 30 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 16, Subject = \"new payment gateway implementation\", Description " +
                    "= \"客户的需求是实现一个\", CompanyName = \"agent database\"},\r\n                new ");
            
            #line 31 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 17, Subject = \"Orchard CMS Maintanece\", Description = \"Message: " +
                    "\", CompanyName = \"\"},\r\n                new ");
            
            #line 32 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 18, Subject = \"nopcommerce template\", Description = \"I would li\"" +
                    ", CompanyName = \"\"},\r\n                new ");
            
            #line 33 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 19, Subject = \"Technical Partner to Outsource\", Description = \"M" +
                    "essage: \", CompanyName = \"\"},\r\n                new ");
            
            #line 34 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 20, Subject = \"a simple nopCommerce plugin\", Description = \"\", C" +
                    "ompanyName = \"\"},\r\n                new ");
            
            #line 35 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 21, Subject = \"get Nopcommerce 2.40 to play uploaded videos\", De" +
                    "scription = \"留言I need h\", CompanyName = \"http://www.mywaycigs.com/\"},\r\n         " +
                    "       new ");
            
            #line 36 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 22, Subject = \"Mobile Project Development\", Description = \"Skype" +
                    "上找到我们\", CompanyName = \"\"},\r\n                new ");
            
            #line 37 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 23, Subject = \"Sedunia Payment Management\", Description = \"\", Co" +
                    "mpanyName = \"GoQuo\"},\r\n                new ");
            
            #line 38 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 24, Subject = \"duplicating registration page on DNN website\", De" +
                    "scription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 39 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 25, Subject = \"Joomla membership site \", Description = \"\", Compa" +
                    "nyName = \"\"},\r\n                new ");
            
            #line 40 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 26, Subject = \"Building a websited with Sitefinity\", Description" +
                    " = \"Nick是一个公司的\", CompanyName = \"\"},\r\n                new ");
            
            #line 41 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 27, Subject = \"Nopcommerce intergration with xero\", Description " +
                    "= \"\", CompanyName = \"Akrom\"},\r\n                new ");
            
            #line 42 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 28, Subject = \"PSD conversion into Sitefinity\", Description = \"M" +
                    "essage: \", CompanyName = \"\"},\r\n                new ");
            
            #line 43 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 29, Subject = \"Changes to Prestashop template\", Description = \"\"" +
                    ", CompanyName = \"ellelocks\"},\r\n                new ");
            
            #line 44 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 30, Subject = \"looking to outsource various projects \", Descript" +
                    "ion = \"\", CompanyName = \"Kitesystems\"},\r\n                new ");
            
            #line 45 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 31, Subject = \"WPAchievements plugin\", Description = \"\", Company" +
                    "Name = \"\"},\r\n                new ");
            
            #line 46 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 32, Subject = \"Offshore Partnership\", Description = \"\", CompanyN" +
                    "ame = \"\"},\r\n                new ");
            
            #line 47 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 33, Subject = \"DNN Developer\", Description = \"\", CompanyName = \"" +
                    "\"},\r\n                new ");
            
            #line 48 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 34, Subject = \"dedicated programer from China\", Description = \"\"" +
                    ", CompanyName = \"BBsecurities\"},\r\n                new ");
            
            #line 49 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 35, Subject = \"Implementing skins for a GUI & Web designer \", De" +
                    "scription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 50 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 36, Subject = \"网站改版升级项目\", Description = \"\", CompanyName = \"\"},\r\n" +
                    "                new ");
            
            #line 51 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 37, Subject = \"FME Would-be Partner\", Description = \"\", CompanyN" +
                    "ame = \"\"},\r\n                new ");
            
            #line 52 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 38, Subject = \"Good Developer on Long Term Basis\", Description =" +
                    " \"德国客户\", CompanyName = \"www.server-ware.com\"},\r\n                new ");
            
            #line 53 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 39, Subject = \"试用CRM\", Description = \"\", CompanyName = \"\"},\r\n   " +
                    "             new ");
            
            #line 54 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 40, Subject = \"汽车养护公司管理系统\", Description = \"客户是做汽车行业的，\", CompanyN" +
                    "ame = \"国宾汽车养护\"},\r\n                new ");
            
            #line 55 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 41, Subject = \"WP Error\", Description = \"\", CompanyName = \"\"},\r\n" +
                    "                new ");
            
            #line 56 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 42, Subject = \"developing NOP commerce plugins\", Description = \"" +
                    "\", CompanyName = \"luminet.si\"},\r\n                new ");
            
            #line 57 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 43, Subject = \"Assistance with nopcommerce development\", Descrip" +
                    "tion = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 58 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 44, Subject = \"A solution for sharing and saving documents to cl" +
                    "ient files\", Description = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 59 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 45, Subject = \"Building a website for a ski resort\", Description" +
                    " = \"判断潜力小且一直没有\", CompanyName = \"\"},\r\n                new ");
            
            #line 60 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 46, Subject = \"website development services \", Description = \"\"," +
                    " CompanyName = \"\"},\r\n                new ");
            
            #line 61 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 47, Subject = \"Customized Mega Menu for Your Website\", Descripti" +
                    "on = \"Message: \", CompanyName = \"Network Fiscale\"},\r\n                new ");
            
            #line 62 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 48, Subject = \"百度轻应用\", Description = \"\", CompanyName = \"\"},\r\n   " +
                    "             new ");
            
            #line 63 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 49, Subject = \"Wordpress plugins for responsive web sites\", Desc" +
                    "ription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 64 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 50, Subject = \"custom nopCommerce skins\", Description = \"\", Comp" +
                    "anyName = \"\"},\r\n                new ");
            
            #line 65 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 51, Subject = \"Annual Costs for 10 devs/testers\", Description = " +
                    "\"Message: \", CompanyName = \"\"},\r\n                new ");
            
            #line 66 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 52, Subject = \"Web application of tracking quotations\", Descript" +
                    "ion = \"\", CompanyName = \"chobble.com\"},\r\n                new ");
            
            #line 67 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 53, Subject = \"Customization to the blog feature\", Description =" +
                    " \"\", CompanyName = \"sitesee.net\"},\r\n                new ");
            
            #line 68 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 54, Subject = \"C++ developer for image segmentation project\", De" +
                    "scription = \"Charles Li\", CompanyName = \"Poikos\"},\r\n                new ");
            
            #line 69 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 55, Subject = \"Cloud Storage System\", Description = \"Message: \"," +
                    " CompanyName = \"\"},\r\n                new ");
            
            #line 70 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 56, Subject = \"New Shopify Store\", Description = \"\", CompanyName" +
                    " = \"\"},\r\n                new ");
            
            #line 71 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 57, Subject = \"UI piece\", Description = \"\", CompanyName = \"\"},\r\n" +
                    "                new ");
            
            #line 72 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 58, Subject = \"Web site with PHP scripts\", Description = \"\", Com" +
                    "panyName = \"Telematcia\"},\r\n                new ");
            
            #line 73 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 59, Subject = \"Hotel Booking Site with NopCommerce\", Description" +
                    " = \"Message: \", CompanyName = \"\"},\r\n                new ");
            
            #line 74 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 60, Subject = \"support Prestashop developer\", Description = \"\", " +
                    "CompanyName = \"\"},\r\n                new ");
            
            #line 75 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 61, Subject = \"Upgrading Magento website\", Description = \"\", Com" +
                    "panyName = \"\"},\r\n                new ");
            
            #line 76 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 62, Subject = \"China Pay\", Description = \"\", CompanyName = \"\"},\r" +
                    "\n                new ");
            
            #line 77 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 63, Subject = \"need .Net developer to complete the website\", Des" +
                    "cription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 78 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 64, Subject = \"PhoneGap App for Free Inner Oracle Cards\", Descri" +
                    "ption = \"做一个纸牌类的游戏，\", CompanyName = \"\"},\r\n                new ");
            
            #line 79 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 65, Subject = \"integrating N2CMS with your existing application\"" +
                    ", Description = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 80 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 66, Subject = \"Amazon Express Checkout plugin for NopCommerce 2." +
                    "4\", Description = \"\", CompanyName = \"inspiredagency.co.uk\"},\r\n                ne" +
                    "w ");
            
            #line 81 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 67, Subject = \"Tryon Function\", Description = \"\", CompanyName = " +
                    "\"\"},\r\n                new ");
            
            #line 82 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 68, Subject = \"Legacy program rewritten\", Description = \"I had a" +
                    " pr\", CompanyName = \"\"},\r\n                new ");
            
            #line 83 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 69, Subject = \"Year Make Model auto parts\", Description = \"\", Co" +
                    "mpanyName = \"\"},\r\n                new ");
            
            #line 84 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 70, Subject = \" long term partnership and first project\", Descri" +
                    "ption = \"\", CompanyName = \"The Small Axe\"},\r\n                new ");
            
            #line 85 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 71, Subject = \"某产权交易中心交易流程管理系统\", Description = \"客户是一家软件开发公\", Com" +
                    "panyName = \"重庆莱基科技有限公司\"},\r\n                new ");
            
            #line 86 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 72, Subject = \"Joomla Extension\", Description = \"\", CompanyName " +
                    "= \"\"},\r\n                new ");
            
            #line 87 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 73, Subject = \"Opencart 1.5.5.1 default theme customization\", De" +
                    "scription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 88 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 74, Subject = \"Sitefinity Reskin 3.7 CMS\", Description = \"Messag" +
                    "e: W\", CompanyName = \"\"},\r\n                new ");
            
            #line 89 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 75, Subject = \"Site Cleaned up and Finish\", Description = \"Messa" +
                    "ge: \", CompanyName = \"\"},\r\n                new ");
            
            #line 90 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 76, Subject = \"Looking for an ASP.NET developer\", Description = " +
                    "\"\", CompanyName = \"\"},\r\n                new ");
            
            #line 91 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 77, Subject = \"Wordpress Page\", Description = \"\", CompanyName = " +
                    "\"\"},\r\n                new ");
            
            #line 92 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 78, Subject = \"hanges on an OC extension\", Description = \"\", Com" +
                    "panyName = \"\"},\r\n                new ");
            
            #line 93 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 79, Subject = \"Long Term Relationship \", Description = \"Hi there" +
                    ", \", CompanyName = \"TheBestAupair \"},\r\n                new ");
            
            #line 94 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 80, Subject = \"HTML5 questionnaire \", Description = \"\", CompanyN" +
                    "ame = \"\"},\r\n                new ");
            
            #line 95 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 81, Subject = \"AX2012 and Nopcommerce integration \", Description" +
                    " = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 96 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 82, Subject = \"Uber-like System\", Description = \"\", CompanyName " +
                    "= \"\"},\r\n                new ");
            
            #line 97 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 83, Subject = \"Webgage Modification on DNN\", Description = \"Mess" +
                    "age: \", CompanyName = \"\"},\r\n                new ");
            
            #line 98 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 84, Subject = \"an external URL \", Description = \"\", CompanyName " +
                    "= \"\"},\r\n                new ");
            
            #line 99 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 85, Subject = \"nopCommerce customization\", Description = \"\", Com" +
                    "panyName = \"\"},\r\n                new ");
            
            #line 100 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 86, Subject = \"OpenCV\", Description = \"Message: I\", CompanyName " +
                    "= \"\"},\r\n                new ");
            
            #line 101 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 87, Subject = \"developing a shopping cart like namecheap.com\", D" +
                    "escription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 102 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 88, Subject = \"Year Make Model\", Description = \"\", CompanyName =" +
                    " \"个人\"},\r\n                new ");
            
            #line 103 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 89, Subject = \"Please contact me\", Description = \"Message: P\", C" +
                    "ompanyName = \"\"},\r\n                new ");
            
            #line 104 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 90, Subject = \".NET MVC 4.5 - JSON Bootstrap. \", Description = \"" +
                    "\", CompanyName = \"\"},\r\n                new ");
            
            #line 105 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 91, Subject = \"Theme implementation for the WordPress Site\", Des" +
                    "cription = \"\", CompanyName = \"\"},\r\n                new ");
            
            #line 106 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 92, Subject = \"Holiday Portal with DNN\", Description = \"Message:" +
                    " H\", CompanyName = \"\"},\r\n                new ");
            
            #line 107 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 93, Subject = \"Building up a Similar Site\", Description = \"Messa" +
                    "ge: \", CompanyName = \"\"},\r\n                new ");
            
            #line 108 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 94, Subject = \"nopCommerce Project\", Description = \"\", CompanyNa" +
                    "me = \"ADC Software\"},\r\n                new ");
            
            #line 109 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 95, Subject = \"Total Costs for a Joomla Website Production\", Des" +
                    "cription = \"Message: \", CompanyName = \"\"},\r\n                new ");
            
            #line 110 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 96, Subject = \"WordPress Plugin\", Description = \"\", CompanyName " +
                    "= \"\"},\r\n                new ");
            
            #line 111 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 97, Subject = \"nopCommerce SSL\", Description = \"\", CompanyName =" +
                    " \"\"},\r\n                new ");
            
            #line 112 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 98, Subject = \"卖场的化妆品的手机APP\", Description = \"打电话来的许先生在为\", Compan" +
                    "yName = \"\"},\r\n                new ");
            
            #line 113 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 99, Subject = \"B2B Website\", Description = \"Message: \", CompanyN" +
                    "ame = \"\"},\r\n                new ");
            
            #line 114 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("PartRecord {Id = 100, Subject = \"Free Trial First\", Description = \"Message: p\", C" +
                    "ompanyName = \"\"}\r\n            };\r\n\r\n            return ");
            
            #line 117 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write("s;\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Lyrix\Desktop\Internship\coevery\Coevery Framework ZJN\Coevery-Framework\src\Coevery.Web\DeveloperTools\CodeGeneration\CodeGenerationTemplates\ApiControllerTemplate.tt"

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private string _ControllerNameField;

/// <summary>
/// Access the ControllerName parameter of the template.
/// </summary>
private string ControllerName
{
    get
    {
        return this._ControllerNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["Namespace"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'Namespace\' did not match the type of t" +
                "he data passed to the template.");
    }
    else
    {
        this._NamespaceField = ((string)(this.Session["Namespace"]));
        NamespaceValueAcquired = true;
    }
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'Namespace\' did not match the type of t" +
                    "he data passed to the template.");
        }
        else
        {
            this._NamespaceField = ((string)(data));
        }
    }
}
bool ControllerNameValueAcquired = false;
if (this.Session.ContainsKey("ControllerName"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["ControllerName"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'ControllerName\' did not match the type" +
                " of the data passed to the template.");
    }
    else
    {
        this._ControllerNameField = ((string)(this.Session["ControllerName"]));
        ControllerNameValueAcquired = true;
    }
}
if ((ControllerNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ControllerName");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'ControllerName\' did not match the type" +
                    " of the data passed to the template.");
        }
        else
        {
            this._ControllerNameField = ((string)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class ApiControllerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
